sudo: required
services: 
    - docker

before_install:
    - docker build -t pavels87/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true pavels87/react-test npm test

after_success:
    - docker build -t pavels87/complex-docker-client ./client
    - docker build -t pavels87/complex-docker-server ./server
    - docker build -t pavels87/complex-docker-worker ./worker
    - docker build -t pavels87/complex-docker-nginx ./nginx

    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    
    - docker push pavels87/complex-docker-client
    - docker push pavels87/complex-docker-server
    - docker push pavels87/complex-docker-worker
    - docker push pavels87/complex-docker-nginx